### ISSUE TITLE
Make it public

### ISSUE THREAD

**Issue by MrTK-Dev** [rHedBull/RSA-App#1]
# Vorschlag

Es hätte den Vorteil, dass wir sowohl ein Wiki (wie genau, welche Funktionen funktionieren / Dokumentation für die Kollaboratoren) als auch eine Website hier hosten können. Diskussion gerne unter dem Issue hier.

# Public Repository

- [x] make it public
- [ ] Add Documentation via WIKI
- [ ] Add Documentation via GitHub-Pages

**Comment by MrTK-Dev** [comment]
# Public Repository

- [ ] Add Documentation via WIKI
- [ ] Add Documentation via GitHub-Pages

**Comment by harrydehix** [comment]
Ich mache für das Wiki und Github Pages eigene Issues, da das jeweils einzelne Fragen sind.
